apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fi8t
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-fi8t@sha256:fbe08b8ae8e69273db43da5125494a9f6221145d00cc705ce5281c67a212a9ce
        name: my-nodejs
        resources: {}
status: {}
